- pkg:maven/org.apache.nifi/nifi-prometheus-utils@1.12.0
- pkg:maven/org.apache.nifi/nifi-prometheus-utils@1.12.0?classifier=sources
- pkg:maven/org.apache.nifi/nifi-prometheus-utils@1.12.1
- pkg:maven/org.apache.nifi/nifi-prometheus-utils@1.12.1?classifier=sources
