- pkg:maven/org.lyranthe.prometheus/macros_2.12.0-RC1@0.2.0
- pkg:maven/org.lyranthe.prometheus/macros_2.12.0-RC1@0.2.0?classifier=sources
- pkg:maven/org.lyranthe.prometheus/macros_2.12.0-RC1@0.3.0
- pkg:maven/org.lyranthe.prometheus/macros_2.12.0-RC1@0.3.0?classifier=sources
