- pkg:maven/dev.linwood/config@3.0.0?classifier=sources
- pkg:maven/dev.linwood/config@3.1.0?classifier=sources
- pkg:maven/dev.linwood/config@3.1.1?classifier=sources
- pkg:maven/dev.linwood/config@3.1.2?classifier=sources
