- pkg:maven/com.facebook.presto/presto-prometheus@0.260.1?classifier=sources
- pkg:maven/com.facebook.presto/presto-prometheus@0.260?classifier=sources
- pkg:maven/com.facebook.presto/presto-prometheus@0.261?classifier=sources
- pkg:maven/com.facebook.presto/presto-prometheus@0.262?classifier=sources
- pkg:maven/com.facebook.presto/presto-prometheus@0.263.1?classifier=sources
- pkg:maven/com.facebook.presto/presto-prometheus@0.263?classifier=sources
- pkg:maven/com.facebook.presto/presto-prometheus@0.264.1?classifier=sources
- pkg:maven/com.facebook.presto/presto-prometheus@0.264?classifier=sources
- pkg:maven/com.facebook.presto/presto-prometheus@0.265.1?classifier=sources
- pkg:maven/com.facebook.presto/presto-prometheus@0.265?classifier=sources
- pkg:maven/com.facebook.presto/presto-prometheus@0.266.1?classifier=sources
- pkg:maven/com.facebook.presto/presto-prometheus@0.266?classifier=sources
- pkg:maven/com.facebook.presto/presto-prometheus@0.267?classifier=sources
- pkg:maven/com.facebook.presto/presto-prometheus@0.268?classifier=sources
- pkg:maven/com.facebook.presto/presto-prometheus@0.269?classifier=sources
- pkg:maven/com.facebook.presto/presto-prometheus@0.270?classifier=sources
- pkg:maven/com.facebook.presto/presto-prometheus@0.271?classifier=sources
- pkg:maven/com.facebook.presto/presto-prometheus@0.272?classifier=sources
