- pkg:maven/com.varwise/prometheus-akka-http_2.12@0.3.4
- pkg:maven/com.varwise/prometheus-akka-http_2.12@0.3.4?classifier=sources
- pkg:maven/com.varwise/prometheus-akka-http_2.12@0.5.0
- pkg:maven/com.varwise/prometheus-akka-http_2.12@0.5.0?classifier=sources
