- pkg:maven/net.wicp.tams/common-flink-connector-prometheus@1.15.1.1
- pkg:maven/net.wicp.tams/common-flink-connector-prometheus@1.15.1.1?classifier=sources
- pkg:maven/net.wicp.tams/common-flink-connector-prometheus@1.17.1.1
- pkg:maven/net.wicp.tams/common-flink-connector-prometheus@1.17.1.1?classifier=sources
- pkg:maven/net.wicp.tams/common-flink-connector-prometheus@1.20.0.1
- pkg:maven/net.wicp.tams/common-flink-connector-prometheus@1.20.0.1?classifier=sources
