- pkg:maven/de.peetzen.dropwizard/dropwizard-metrics-prometheus-servlet-bundle@1.0.0-RC2?classifier=sources
- pkg:maven/de.peetzen.dropwizard/dropwizard-metrics-prometheus-servlet-bundle@1.0.0-rc1?classifier=sources
- pkg:maven/de.peetzen.dropwizard/dropwizard-metrics-prometheus-servlet-bundle@1.0.0?classifier=sources
- pkg:maven/de.peetzen.dropwizard/dropwizard-metrics-prometheus-servlet-bundle@3.0.0?classifier=sources
- pkg:maven/de.peetzen.dropwizard/dropwizard-metrics-prometheus-servlet-bundle@3.0.1?classifier=sources
- pkg:maven/de.peetzen.dropwizard/dropwizard-metrics-prometheus-servlet-bundle@3.0.2?classifier=sources
- pkg:maven/de.peetzen.dropwizard/dropwizard-metrics-prometheus-servlet-bundle@4.0.0?classifier=sources
- pkg:maven/de.peetzen.dropwizard/dropwizard-metrics-prometheus-servlet-bundle@4.0.1?classifier=sources
- pkg:maven/de.peetzen.dropwizard/dropwizard-metrics-prometheus-servlet-bundle@4.0.2?classifier=sources
