- pkg:maven/com.softwaremill.sttp.client3/prometheus-backend_3@3.3.6
- pkg:maven/com.softwaremill.sttp.client3/prometheus-backend_3@3.3.6?classifier=sources
- pkg:maven/com.softwaremill.sttp.client3/prometheus-backend_3@3.3.7
- pkg:maven/com.softwaremill.sttp.client3/prometheus-backend_3@3.3.7?classifier=sources
- pkg:maven/com.softwaremill.sttp.client3/prometheus-backend_3@3.3.9
- pkg:maven/com.softwaremill.sttp.client3/prometheus-backend_3@3.3.9?classifier=sources
