- pkg:maven/com.bq.corbel.lib/config@0.3.0
- pkg:maven/com.bq.corbel.lib/config@0.3.0?classifier=sources
- pkg:maven/com.bq.corbel.lib/config@0.4.0
- pkg:maven/com.bq.corbel.lib/config@0.4.0?classifier=sources
- pkg:maven/com.bq.corbel.lib/config@0.4.1
- pkg:maven/com.bq.corbel.lib/config@0.4.1?classifier=sources
