- pkg:maven/com.vectorprint/Config@1.0
- pkg:maven/com.vectorprint/Config@1.0?classifier=sources
- pkg:maven/com.vectorprint/Config@1.1
- pkg:maven/com.vectorprint/Config@1.1?classifier=sources
- pkg:maven/com.vectorprint/Config@1.6
- pkg:maven/com.vectorprint/Config@1.6?classifier=sources
- pkg:maven/com.vectorprint/Config@1.7
- pkg:maven/com.vectorprint/Config@1.7?classifier=sources
- pkg:maven/com.vectorprint/Config@5.0
- pkg:maven/com.vectorprint/Config@5.0?classifier=sources
- pkg:maven/com.vectorprint/Config@5.2
- pkg:maven/com.vectorprint/Config@5.2?classifier=sources
- pkg:maven/com.vectorprint/Config@5.3
- pkg:maven/com.vectorprint/Config@5.3?classifier=sources
- pkg:maven/com.vectorprint/Config@5.5
- pkg:maven/com.vectorprint/Config@5.5?classifier=sources
