- pkg:maven/com.vectorprint/Config@1.0
- pkg:maven/com.vectorprint/Config@1.0?classifier=sources
- pkg:maven/com.vectorprint/Config@1.1
- pkg:maven/com.vectorprint/Config@1.1?classifier=sources
- pkg:maven/com.vectorprint/Config@1.6
- pkg:maven/com.vectorprint/Config@1.6?classifier=sources
- pkg:maven/com.vectorprint/Config@1.7
- pkg:maven/com.vectorprint/Config@1.7?classifier=sources
- pkg:maven/com.vectorprint/Config@10.0
- pkg:maven/com.vectorprint/Config@10.0?classifier=sources
- pkg:maven/com.vectorprint/Config@10.1
- pkg:maven/com.vectorprint/Config@10.1?classifier=sources
- pkg:maven/com.vectorprint/Config@10.2
- pkg:maven/com.vectorprint/Config@10.2?classifier=sources
- pkg:maven/com.vectorprint/Config@10.3
- pkg:maven/com.vectorprint/Config@10.3?classifier=sources
- pkg:maven/com.vectorprint/Config@10.5
- pkg:maven/com.vectorprint/Config@10.5?classifier=sources
- pkg:maven/com.vectorprint/Config@10.6
- pkg:maven/com.vectorprint/Config@10.6?classifier=sources
- pkg:maven/com.vectorprint/Config@10.7
- pkg:maven/com.vectorprint/Config@10.7?classifier=sources
- pkg:maven/com.vectorprint/Config@10.8
- pkg:maven/com.vectorprint/Config@10.8?classifier=sources
- pkg:maven/com.vectorprint/Config@10.9
- pkg:maven/com.vectorprint/Config@10.9?classifier=sources
- pkg:maven/com.vectorprint/Config@11.0
- pkg:maven/com.vectorprint/Config@11.0?classifier=sources
- pkg:maven/com.vectorprint/Config@11.1
- pkg:maven/com.vectorprint/Config@11.1?classifier=sources
- pkg:maven/com.vectorprint/Config@11.2
- pkg:maven/com.vectorprint/Config@11.2?classifier=sources
- pkg:maven/com.vectorprint/Config@11.4
- pkg:maven/com.vectorprint/Config@11.4?classifier=sources
- pkg:maven/com.vectorprint/Config@11.5
- pkg:maven/com.vectorprint/Config@11.5?classifier=sources
- pkg:maven/com.vectorprint/Config@12.0
- pkg:maven/com.vectorprint/Config@12.0?classifier=sources
- pkg:maven/com.vectorprint/Config@12.1
- pkg:maven/com.vectorprint/Config@12.1?classifier=sources
- pkg:maven/com.vectorprint/Config@12.2
- pkg:maven/com.vectorprint/Config@12.2?classifier=sources
- pkg:maven/com.vectorprint/Config@13.0
- pkg:maven/com.vectorprint/Config@13.0?classifier=sources
- pkg:maven/com.vectorprint/Config@13.2
- pkg:maven/com.vectorprint/Config@13.2?classifier=sources
- pkg:maven/com.vectorprint/Config@13.3
- pkg:maven/com.vectorprint/Config@13.3?classifier=sources
- pkg:maven/com.vectorprint/Config@14.0
- pkg:maven/com.vectorprint/Config@14.0?classifier=sources
- pkg:maven/com.vectorprint/Config@14.1
- pkg:maven/com.vectorprint/Config@14.1?classifier=sources
- pkg:maven/com.vectorprint/Config@15.0?classifier=sources
- pkg:maven/com.vectorprint/Config@15.1?classifier=sources
- pkg:maven/com.vectorprint/Config@16.0?classifier=sources
- pkg:maven/com.vectorprint/Config@5.0
- pkg:maven/com.vectorprint/Config@5.0?classifier=sources
- pkg:maven/com.vectorprint/Config@5.2
- pkg:maven/com.vectorprint/Config@5.2?classifier=sources
- pkg:maven/com.vectorprint/Config@5.3
- pkg:maven/com.vectorprint/Config@5.3?classifier=sources
- pkg:maven/com.vectorprint/Config@5.5
- pkg:maven/com.vectorprint/Config@5.5?classifier=sources
- pkg:maven/com.vectorprint/Config@6.0
- pkg:maven/com.vectorprint/Config@6.0?classifier=sources
- pkg:maven/com.vectorprint/Config@6.1
- pkg:maven/com.vectorprint/Config@6.1?classifier=sources
- pkg:maven/com.vectorprint/Config@6.2
- pkg:maven/com.vectorprint/Config@6.2?classifier=sources
- pkg:maven/com.vectorprint/Config@6.3
- pkg:maven/com.vectorprint/Config@6.3?classifier=sources
- pkg:maven/com.vectorprint/Config@6.5
- pkg:maven/com.vectorprint/Config@6.5?classifier=sources
- pkg:maven/com.vectorprint/Config@6.6
- pkg:maven/com.vectorprint/Config@6.6?classifier=sources
- pkg:maven/com.vectorprint/Config@6.7
- pkg:maven/com.vectorprint/Config@6.7?classifier=sources
- pkg:maven/com.vectorprint/Config@6.8
- pkg:maven/com.vectorprint/Config@6.8?classifier=sources
- pkg:maven/com.vectorprint/Config@7.0
- pkg:maven/com.vectorprint/Config@7.0?classifier=sources
- pkg:maven/com.vectorprint/Config@7.2
- pkg:maven/com.vectorprint/Config@7.2?classifier=sources
- pkg:maven/com.vectorprint/Config@7.4
- pkg:maven/com.vectorprint/Config@7.4?classifier=sources
- pkg:maven/com.vectorprint/Config@8.0
- pkg:maven/com.vectorprint/Config@8.0?classifier=sources
- pkg:maven/com.vectorprint/Config@8.2
- pkg:maven/com.vectorprint/Config@8.2?classifier=sources
- pkg:maven/com.vectorprint/Config@8.3
- pkg:maven/com.vectorprint/Config@8.3?classifier=sources
- pkg:maven/com.vectorprint/Config@8.5
- pkg:maven/com.vectorprint/Config@8.5?classifier=sources
- pkg:maven/com.vectorprint/Config@8.6
- pkg:maven/com.vectorprint/Config@8.6?classifier=sources
- pkg:maven/com.vectorprint/Config@9.1
- pkg:maven/com.vectorprint/Config@9.1?classifier=sources
